image: python:3.7.2-slim

test:
  stage: test
  script:
  - pip install -r requirements.txt
  - sphinx-build -b html . public
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
  - pip install -r requirements.txt
  - sphinx-build -b html . public
  - cp Page/* public/
  - cp Docs/hhu-logo.png public/_static/hhu-logo.png
  artifacts:
    paths:
    - public
  only:
  - master
